### ISSUE TITLE
undefined variables in obs_generator.py

### ISSUE THREAD

**Issue by aliciacanipe** [spacetelescope/nircam_simulator#78]
I was trying to use the simulator on an input dark exposure, and it errored out on the invert_ipc_kernel function (inside obs_generator.py) with a NameError, I think because "nyc" and "nyx" are not defined.

**Comment by bhilbert4** [comment]
I put in a fix for this yesterday afternoon. Try pulling the repo again and rerunning. Let me know if you still have problems.

**Comment by aliciacanipe** [comment]
Oh, sorry. Thanks, I'll give it a shot!
